development:
  SENDGRID_USERNAME: HowardSnowden  
  SENDGRID_PASSWORD: Bastard4224!
  SENDGRID_DOMAIN:   localhost:3000
production:
  SENDGRID_USERNAME: HowardSnowden  
  SENDGRID_PASSWORD: Bastard4224!
  SENDGRID_DOMAIN:   http://gentle-tundra-5066.herokuapp.com
  stripe_publishable_key: pk_test_sL0dMDZV5OyGHQ4WZhHsv7jK
  stripe_secret_key: sk_test_tWxvZ4QdMcnmupgRj70Q7i28